# @package _global_

#### Model params #############################################################
model:
  name: stgnn
  hparams:
    hidden_size: 256
    emb_size: 32
    add_embedding_before: ['encoding', 'message_passing', 'decoding']
    time_layers: 2
    graph_layers: 4
    activation: 'elu'
    noise_mode: 'lin'
    time_skip_connect: true

dataset:
  connectivity:
    layout: csr



